### CreateEvent
POST http://localhost:3333/events
Content-Type: application/json

{
"title": "Unite Api Summit",
"details": "Um evento para quem é apaixonado por programação",
"maximumAttendees": 1
}

### RegisterForEvent
POST http://localhost:3333/events/92b6ddc6-de05-4992-99b3-3eda8c90919a/attendees
Content-Type: application/json

{
"name": "Lucas Gimenes",
"email": "wlb.lucas2@gmail.com"
}

### GetEvent
GET http://localhost:3333/events/176f5263-d395-4d27-ba5a-caaa7a5aad82

### GetAttendeeBadge
GET http://localhost:3333/attendees/5/badge

### GetAttendeeCheckin
GET http://localhost:3333/attendees/5/check-in

### GetEventAttendiees
GET http://localhost:3333/events/92b6ddc6-de05-4992-99b3-3eda8c90919a/attendees?query=lucas